#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 1.0.0.{build}
environment:
  PowerShellGalleryApiKey:
    secure: 1dvlzHXj42LofdFsQADx+JH5T3rGvzgvcA2XzIWI/5h9TeCSD8EQU+ELD6PaXvOc
  GitHubPushFromPlagueHO:
    secure: T1YH80PnRtYOlW3XM6rYkavs91a+Dr37V9ln0OX1UrVYUoNHaJq0paGswPEWKraL

build_script:
  - ps: . .\build.ps1 -Deploy
